# -*- coding: utf-8 -*-
"""lstm_air_passengers.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1II2KAR2gh0slgk89MwZM-UNkXw9hOpxu
"""

#my code

# lstm_air_passengers.py

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.preprocessing import MinMaxScaler
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, LSTM
from tensorflow.keras.callbacks import EarlyStopping

# Step 1: Load the data
df = pd.read_csv("/content/AirPassengers.csv")
df.columns = ["Month", "Passengers"]  # Clean column names
df['Month'] = pd.to_datetime(df['Month'])
df.set_index('Month', inplace=True)

# Step 2: Normalize the data
scaler = MinMaxScaler()
scaled_data = scaler.fit_transform(df[['Passengers']])

# Step 3: Create sequences
def create_sequences(data, time_steps=12):
    X, y = [], []
    for i in range(len(data) - time_steps):
        X.append(data[i:i + time_steps])
        y.append(data[i + time_steps])
    return np.array(X), np.array(y)

time_steps = 12
X, y = create_sequences(scaled_data, time_steps)

# Step 4: Split data (80% train, 20% test)
split = int(0.8 * len(X))
X_train, X_test = X[:split], X[split:]
y_train, y_test = y[:split], y[split:]

# Step 5: Build the LSTM model
model = Sequential([
    LSTM(50, activation='relu', input_shape=(time_steps, 1)),
    Dense(1)
])
model.compile(optimizer='adam', loss='mse')

# Step 6: Train the model
early_stop = EarlyStopping(monitor='val_loss', patience=10)
history = model.fit(
    X_train, y_train,
    validation_data=(X_test, y_test),
    epochs=100,
    batch_size=16,
    callbacks=[early_stop],
    verbose=1
)

# Step 7: Predict and inverse scale
predicted = model.predict(X_test)
predicted = scaler.inverse_transform(predicted)
y_test_true = scaler.inverse_transform(y_test)

# Step 8: Plot results
plt.figure(figsize=(10,6))
plt.plot(y_test_true, label="Actual")
plt.plot(predicted, label="Predicted")
plt.title("Air Passengers Forecasting with LSTM")
plt.xlabel("Time Step")
plt.ylabel("Number of Passengers")
plt.legend()
plt.grid(True)
plt.show()